version: 0.2

phases:
  pre_build:
    commands:
      - echo resolved source version $CODEBUILD_RESOLVED_SOURCE_VERSION
  build:
    commands:
      - echo Build started on `date`
      - echo Running tests
      - npm run test
  post_build:
    commands:
      - echo Build completed on `date`
